version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8080:8080"
  jaeger-allinone:
    image: jaegertracing/all-in-one:1.39
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
