version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8080:8080"
  jaeger:
    image: jaegertracing/all-in-one:1.39
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
