version: '3.8'

services:
  backend:
    container_name: backend
    build:
      dockerfile: docker/api.dockerfile
      context: ..
    ports:
      - "8080:8080"
  jaeger-allinone:
    image: jaegertracing/all-in-one:1.39
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    ports:
      - "9000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
